/* 
 * AVM
 *
 * This is api for AVM (automated valuation machine)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@enbisys.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Enbisys.AVM.Client.OpenAPIDateConverter;

namespace Enbisys.AVM.Model
{
    /// <summary>
    /// Defines EnergyEfficiency
    /// </summary>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum EnergyEfficiency
    {
        /// <summary>
        /// Enum Average for value: average
        /// </summary>
        [EnumMember(Value = "average")]
        Average = 1,

        /// <summary>
        /// Enum Good for value: good
        /// </summary>
        [EnumMember(Value = "good")]
        Good = 2,

        /// <summary>
        /// Enum Poor for value: poor
        /// </summary>
        [EnumMember(Value = "poor")]
        Poor = 3,

        /// <summary>
        /// Enum Verygood for value: very_good
        /// </summary>
        [EnumMember(Value = "very_good")]
        Verygood = 4,

        /// <summary>
        /// Enum Verypoor for value: very_poor
        /// </summary>
        [EnumMember(Value = "very_poor")]
        Verypoor = 5

    }

}
