/* 
 * AVM
 *
 * This is api for AVM (automated valuation machine)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@enbisys.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Enbisys.AVM.Client.OpenAPIDateConverter;

namespace Enbisys.AVM.Model
{
    /// <summary>
    /// Floor level
    /// </summary>
    /// <value>Floor level</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum FloorLevel
    {
        /// <summary>
        /// Enum Basement for value: basement
        /// </summary>
        [EnumMember(Value = "basement")]
        Basement = 1,

        /// <summary>
        /// Enum Ground for value: ground
        /// </summary>
        [EnumMember(Value = "ground")]
        Ground = 2,

        /// <summary>
        /// Enum Middle for value: middle
        /// </summary>
        [EnumMember(Value = "middle")]
        Middle = 3,

        /// <summary>
        /// Enum Top for value: top
        /// </summary>
        [EnumMember(Value = "top")]
        Top = 4,

        /// <summary>
        /// Enum Floor1 for value: floor_1
        /// </summary>
        [EnumMember(Value = "floor_1")]
        Floor1 = 5,

        /// <summary>
        /// Enum Floor2 for value: floor_2
        /// </summary>
        [EnumMember(Value = "floor_2")]
        Floor2 = 6,

        /// <summary>
        /// Enum Floor3 for value: floor_3
        /// </summary>
        [EnumMember(Value = "floor_3")]
        Floor3 = 7,

        /// <summary>
        /// Enum Floor4 for value: floor_4
        /// </summary>
        [EnumMember(Value = "floor_4")]
        Floor4 = 8,

        /// <summary>
        /// Enum Floor5 for value: floor_5
        /// </summary>
        [EnumMember(Value = "floor_5")]
        Floor5 = 9,

        /// <summary>
        /// Enum Floor6 for value: floor_6
        /// </summary>
        [EnumMember(Value = "floor_6")]
        Floor6 = 10,

        /// <summary>
        /// Enum Floor7 for value: floor_7
        /// </summary>
        [EnumMember(Value = "floor_7")]
        Floor7 = 11,

        /// <summary>
        /// Enum Floor8 for value: floor_8
        /// </summary>
        [EnumMember(Value = "floor_8")]
        Floor8 = 12,

        /// <summary>
        /// Enum Floor9 for value: floor_9
        /// </summary>
        [EnumMember(Value = "floor_9")]
        Floor9 = 13,

        /// <summary>
        /// Enum Floor10 for value: floor_10
        /// </summary>
        [EnumMember(Value = "floor_10")]
        Floor10 = 14,

        /// <summary>
        /// Enum Floor11 for value: floor_11
        /// </summary>
        [EnumMember(Value = "floor_11")]
        Floor11 = 15,

        /// <summary>
        /// Enum Floor12 for value: floor_12
        /// </summary>
        [EnumMember(Value = "floor_12")]
        Floor12 = 16,

        /// <summary>
        /// Enum Floor13 for value: floor_13
        /// </summary>
        [EnumMember(Value = "floor_13")]
        Floor13 = 17,

        /// <summary>
        /// Enum Floor14 for value: floor_14
        /// </summary>
        [EnumMember(Value = "floor_14")]
        Floor14 = 18,

        /// <summary>
        /// Enum Floor15 for value: floor_15
        /// </summary>
        [EnumMember(Value = "floor_15")]
        Floor15 = 19,

        /// <summary>
        /// Enum Floor16 for value: floor_16
        /// </summary>
        [EnumMember(Value = "floor_16")]
        Floor16 = 20,

        /// <summary>
        /// Enum Floor17 for value: floor_17
        /// </summary>
        [EnumMember(Value = "floor_17")]
        Floor17 = 21,

        /// <summary>
        /// Enum Floor18 for value: floor_18
        /// </summary>
        [EnumMember(Value = "floor_18")]
        Floor18 = 22,

        /// <summary>
        /// Enum Floor19 for value: floor_19
        /// </summary>
        [EnumMember(Value = "floor_19")]
        Floor19 = 23,

        /// <summary>
        /// Enum Floor20 for value: floor_20
        /// </summary>
        [EnumMember(Value = "floor_20")]
        Floor20 = 24,

        /// <summary>
        /// Enum Floor21orabove for value: floor_21_or_above
        /// </summary>
        [EnumMember(Value = "floor_21_or_above")]
        Floor21orabove = 25

    }

}
