/* 
 * AVM
 *
 * This is api for AVM (automated valuation machine)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@enbisys.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Enbisys.AVM.Client.OpenAPIDateConverter;

namespace Enbisys.AVM.Model
{
    /// <summary>
    /// Defines LeaseholdOrFreehold
    /// </summary>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum LeaseholdOrFreehold
    {
        /// <summary>
        /// Enum Freehold for value: freehold
        /// </summary>
        [EnumMember(Value = "freehold")]
        Freehold = 1,

        /// <summary>
        /// Enum Leasehold for value: leasehold
        /// </summary>
        [EnumMember(Value = "leasehold")]
        Leasehold = 2

    }

}
