/* 
 * AVM
 *
 * This is api for AVM (automated valuation machine)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@enbisys.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Enbisys.AVM.Client.OpenAPIDateConverter;

namespace Enbisys.AVM.Model
{
    /// <summary>
    /// type of property
    /// </summary>
    /// <value>type of property</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum PropertyType
    {
        /// <summary>
        /// Enum Flat for value: flat
        /// </summary>
        [EnumMember(Value = "flat")]
        Flat = 1,

        /// <summary>
        /// Enum Semidetachedhouse for value: semi_detached_house
        /// </summary>
        [EnumMember(Value = "semi_detached_house")]
        Semidetachedhouse = 2,

        /// <summary>
        /// Enum Detachedhouse for value: detached_house
        /// </summary>
        [EnumMember(Value = "detached_house")]
        Detachedhouse = 3,

        /// <summary>
        /// Enum Terracedhouse for value: terraced_house
        /// </summary>
        [EnumMember(Value = "terraced_house")]
        Terracedhouse = 4

    }

}
