/* 
 * AVM
 *
 * This is api for AVM (automated valuation machine)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@enbisys.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Enbisys.AVM.Client.OpenAPIDateConverter;

namespace Enbisys.AVM.Model
{
    /// <summary>
    /// Defines RoofType
    /// </summary>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum RoofType
    {
        /// <summary>
        /// Enum Pitched for value: pitched
        /// </summary>
        [EnumMember(Value = "pitched")]
        Pitched = 1,

        /// <summary>
        /// Enum Flat for value: flat
        /// </summary>
        [EnumMember(Value = "flat")]
        Flat = 2,

        /// <summary>
        /// Enum Thatched for value: thatched
        /// </summary>
        [EnumMember(Value = "thatched")]
        Thatched = 3,

        /// <summary>
        /// Enum Dwelling for value: dwelling
        /// </summary>
        [EnumMember(Value = "dwelling")]
        Dwelling = 4

    }

}
