/* 
 * AVM
 *
 * This is api for AVM (automated valuation machine)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@enbisys.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Enbisys.AVM.Client.OpenAPIDateConverter;

namespace Enbisys.AVM.Model
{
    /// <summary>
    /// Defines WallType
    /// </summary>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum WallType
    {
        /// <summary>
        /// Enum Cavitywall for value: cavity_wall
        /// </summary>
        [EnumMember(Value = "cavity_wall")]
        Cavitywall = 1,

        /// <summary>
        /// Enum Cob for value: cob
        /// </summary>
        [EnumMember(Value = "cob")]
        Cob = 2,

        /// <summary>
        /// Enum Graniteorwhin for value: granite_or_whin
        /// </summary>
        [EnumMember(Value = "granite_or_whin")]
        Graniteorwhin = 3,

        /// <summary>
        /// Enum Parkhomewall for value: park_home_wall
        /// </summary>
        [EnumMember(Value = "park_home_wall")]
        Parkhomewall = 4,

        /// <summary>
        /// Enum Sandstone for value: sandstone
        /// </summary>
        [EnumMember(Value = "sandstone")]
        Sandstone = 5,

        /// <summary>
        /// Enum Solidbrick for value: solid_brick
        /// </summary>
        [EnumMember(Value = "solid_brick")]
        Solidbrick = 6,

        /// <summary>
        /// Enum Systembuild for value: system_build
        /// </summary>
        [EnumMember(Value = "system_build")]
        Systembuild = 7,

        /// <summary>
        /// Enum Timberframe for value: timber_frame
        /// </summary>
        [EnumMember(Value = "timber_frame")]
        Timberframe = 8

    }

}
